targets:
  $default:
    builders:
      bloc_gen_plus|bloc_builder:
        enabled: true
        generate_for:
          - lib/bloc/*.yaml
      bloc_gen_plus|i18n_builder:
        enabled: true
        generate_for:
          - lib/i18n/*.yaml

