builders:
  i18n_builder:
    import: 'package:bloc_generator/bloc_generator.dart'
    builder_factories: ['i18nBuilder']
    build_extensions: {'.yaml': ['.i18n.dart']}
    auto_apply: dependents
    build_to: source

  bloc_builder:
    import: 'package:bloc_generator/bloc_generator.dart'
    builder_factories: ['blocBuilder']
    build_extensions: {
      'demo.yaml': [
        'demobloc/demo.dart',
        'demobloc/demo.s.dart',
        'demobloc/demo.e.dart',
        'demobloc/demo.b.dart',
        'demobloc/demo.d.dart',
        'demobloc/demo.c.dart'
      ],
      'demo_parent.yaml': [
        'demo_parent/demo_parent.dart',
        'demo_parent/demo_parent.s.dart',
        'demo_parent/demo_parent.e.dart',
        'demo_parent/demo_parent.b.dart',
        'demo_parent/demo_parent.d.dart',
        'demo_parent/demo_parent.c.dart'
      ],
      'state_only.yaml': [
        'demostate/demo.dart',
        'demostate/demo.s.dart',
        'demostate/demo.e.dart',
        'demostate/demo.b.dart',
        'demostate/demo.d.dart',
        'demostate/demo.c.dart'
      ],
      'event_only.yaml': [
        'demoevent/demo.dart',
        'demoevent/demo.s.dart',
        'demoevent/demo.e.dart',
        'demoevent/demo.b.dart',
        'demoevent/demo.d.dart',
        'demoevent/demo.c.dart'
      ],
      '.yaml': [
        '.dart',
        '.s.dart',
        '.e.dart',
        '.b.dart',
        '.d.dart',
        '.c.dart'
      ]
    }
    auto_apply: dependents
    build_to: source
    runs_before: ["json_serializable:json_serializable"]
